config/routes.rb
Wjgzxt::Application.routes.draw do
  match 'log' => 'log_action#index'
  match 'log(/:action)' => 'log_action#(:action)'
  resources :log_action,only:[:index] do
    collection do
      get 'index','neg_r','neg_ru'
    end
  end

  resources :pwd_modify, only: [] do
    collection do
      get 'modify', 'p_modify'
    end
  end

  resources :domain, only: [] do
    collection do
      get 'validate', 'test', 'dfileupload'
      post 'upload'
    end
  end

  resources :export, only: [] do
    member do
      get 'modify', 'chg_status', 'del'
    end
    collection do
      get 'index', 'flag', 'perm_deni'
      get 'mdf', 'add_flag', 'p_add_flag'
    end
  end

  resources :rdata, only: [] do
    collection do
      get 'index','q_rdata_report'
    end
  end

  match 'login' => 'login#index'
  get 'login/index'
  post "login/login"
  get "login/logout"

  match 'workorders' => 'workorders#index'
  resources :workorders, only: [] do
    collection do
      get 'index', 'day_wo', 'week_wo', 'month_wo', 'wo_table', 'export_detail', 'week_table', 'month_table'
    end
  end

  match 'graphs' => 'graphs#index'
  resources :graphs, only: [] do
    collection do
      get 'index', 'data_json'
    end
  end

  resources :web_hit_rate, only: [] do
    collection do
      get 'time_r', 'select_day_report', 'select_month_report', 'index', 'day_r', 'month_r', 'list_day', 'list_time', 'list_locale'
      post 'day_r', 'month_r'
    end
  end

  match 'whr/' => 'web_hit_rate#index'

  resources :param_setting, only: [] do
    collection do
      get 'http', 'ping', 'route', 'video', 'adduser', 'mng_user', 'interaction', 'view_interaction', 'del_interaction', 'p_adduser'
      get 'u_user', 's_user', 'd_user', 'p_u_user', 'p_interaction'
      post 'p_adduser'
    end
  end

  match 'reports/get_data(.:format)' => 'reports#get_data'
  resources :reports, only: [] do
    collection do
      get 'export_rep', 'get_data', 'r_graph', 'locale_detail'
      get 'select_date_report', 'select_day_report', 'select_week_report', 'select_month_report'
      get 'time_report', 'day_report', 'week_report', 'month_report', 'day_report_csv', 'week_report_csv', 'month_report_csv'
      get 'date2time_report', 'date2day_report', 'date2week_report', 'date2month_report'
      post 'day_report', 'week_report', 'month_report'
    end
  end

  get 'reports/export_ranking'

  post 'reports/website_ranking'

  get 'reports/website_select'

  get 'reports/locale_ranking'

  get 'welcome/index'

  match 'reports/' => 'reports#index'
  match 'welcome/' => 'welcome#index'

  root :to => 'login#index'

end

app/controllers/workorders_controller.rb
#encoding : utf-8
require 'will_paginate/array'

class WorkordersController < ApplicationController
  def index
  end

  def wo_table
    #通过用户获得其所管辖的出口
    user      = User.find(session[:user_id])
    e_name    = user.export_names
    @dls_name = user.alias

    #工单显示的顺序从当前往后排列,先保存当月的数据
    t_year    = Time.now.year
    t_day     = Time.now.day
    t_month   = Time.now.month

    p_year  = 0
    p_day   = 1
    p_month = 0
    #显示最近两个月的日报表数据
    #首先判断一下是不是在1月
    if t_month == 1
      p_month = 12
      p_year  = t_year -1
    else
      p_month = t_month - 1
      p_year  = t_year
    end

    #获得上一个月的最大天数
    p_str      = p_year.to_s + '-' + p_month.to_s + '-' + p_day.to_s
    p_date     = Time.parse(p_str)
    p_min_day  = 1
    p_max_day  = p_date.at_end_of_month.day


    #列出当前月的数据统计,如果是当月1日，则直接略过当月的数据，直接显示前一个月即可。
    @out_arr   = []
    all_in_one = []
    unless t_day == 1
      c_day = t_day -1
      while c_day >= 1
        c_str    = t_year.to_s + '-' + t_month.to_s + '-' + c_day.to_s
        c_b_date = Time.parse(c_str)
        rl       = ReportLog.where('r_date = ? and user_id = ? and r_type = "day"', c_b_date, user.id)
        tmp_arr  = []
        tmp_arr << c_b_date << '所有关联出口日报表'
        tmp_arr << rl[0].view_date unless rl.blank?
        all_in_one << tmp_arr
        c_day -= 1
      end
    end

    #列出前一个月的数据统计
    while p_max_day >= 1
      p_str    = p_year.to_s + '-' + p_month.to_s + '-' + p_max_day.to_s
      p_b_date = Time.parse(p_str)
      rl       = ReportLog.where('r_date = ? and user_id = ? and r_type = "day"', p_b_date, user.id)
      tmp_arr  = []
      tmp_arr << p_b_date << '所有关联出口日报表'
      tmp_arr << rl[0].view_date unless rl.blank?
      all_in_one << tmp_arr
      p_max_day -= 1
    end

    @out_arr = all_in_one.paginate page: params[:page], per_page: 10
  end

  def day_wo
    #通过用户获得其所管辖的出口
    user      = User.find(session[:user_id])
    e_name    = user.export_names
    @dls_name = user.alias

    r_date = Time.parse params[:date]

    @out_arr = []
    @out_arr = statis_d_data(e_name, r_date, 1)
    puts '-'*100
    puts r_date
    puts '-'*100
    ReportLog.create(r_type: 'day', r_date: r_date, user_id: user.id, view_date: Time.now)
    render :template => 'workorders/out_template'
  end

=begin
  def day_wo1
    #通过用户获得其所管辖的出口
    user      = User.first
    e_name    = user.export_names
    @dls_name = user.alias

    #工单显示的顺序从当前往后排列,先保存当月的数据
    t_year    = Time.now.year
    t_day     = Time.now.day
    t_month   = Time.now.month

    p_year  = 0
    p_day   = 1
    p_month = 0
    #显示最近两个月的日报表数据
    #首先判断一下是不是在1月
    if t_month == 1
      p_month = 12
      p_year  = t_year -1
    else
      p_month = t_month - 1
      p_year  = t_year
    end

    #获得上一个月的最大天数
    p_str     = p_year.to_s + '-' + p_month.to_s + '-' + p_day.to_s
    p_date    = Time.parse(p_str)
    p_min_day = 1
    p_max_day = p_date.at_end_of_month.day

    #列出当前月的数据统计,如果是当月1日，则直接略过当月的数据，直接显示前一个月即可。
    @out_arr  = []
    unless t_day == 1
      c_day = t_day -1
      while c_day >= 1
        @out_arr += statis_d_data1(e_name, c_day, t_month, t_year)
        c_day    -= 1
      end
    end

    #列出前一个月的数据统计
    while p_max_day >= 1
      @out_arr  += statis_d_data1(e_name, p_max_day, p_month, p_year)
      p_max_day -= 1
    end
    render :template => 'workorders/out_template'
  end
=end


  def export_detail
    #现在是统计一天的数据
    @q_export = params[:ename]
    snn = ExportName.find_by_name(@q_export).alias
    b_time    = Time.parse(params[:bdate])
    e_time    = Time.parse(params[:edate])
    #只查询出来那些测试为负的数据。
    @q_data   = HttpTestScore.where('source_node_name = ? and test_time >= ? and test_time < ? and negative_items_scores < ?', snn, b_time, e_time, 0).order('negative_items_scores').paginate page: params[:page], per_page: 10
  end

  def week_table
    #通过用户获得其所管辖的出口
    user      = User.find(session[:user_id])
    e_name    = user.export_names
    @dls_name = user.alias

    #工单显示的是最近8个星期的统计数据,从周一到周末，如果为周一，则加多一个星期
    t_year    = Time.now.year
    t_day     = Time.now.at_beginning_of_day
    t_wb_day  = Time.now.at_beginning_of_week
    t_we_day  = Time.now.at_end_of_week
    t_month   = Time.now.month

    @out_arr = []
    if t_day == t_wb_day
      #为周1则需要加多一个星期
      (1..8).each do |num|
        tmp_arr = []
        t_wb    = t_wb_day - num.week
        t_we    = t_we_day - num.week
        rl      = ReportLog.where('r_date = ? and user_id = ? and r_type = "week"', t_wb, user.id)

        tmp_arr << t_wb << t_we << '所有关联出口周报表'
        tmp_arr << rl[0].view_date unless rl.blank?
        @out_arr << tmp_arr
      end
    else
      #不是周1的情况则按正常排序即可
      (0..7).each do |num|
        tmp_arr = []
        t_wb    = t_wb_day - num.week
        if num == 0
          t_we = t_day
        else
          t_we = t_we_day - num.week
        end
        rl = ReportLog.where('r_date = ? and user_id = ? and r_type = "week"', t_wb, user.id)

        tmp_arr << t_wb << t_we << '所有关联出口周报表'
        tmp_arr << rl[0].view_date unless rl.blank?
        @out_arr << tmp_arr
      end
    end
  end

  def week_wo
    #通过用户获得其所管辖的出口
    user      = User.find(session[:user_id])
    e_name    = user.export_names
    @dls_name = user.alias
    r_date    = Time.parse params[:date]
    @out_arr  = statis_d_data(e_name, r_date, 2)

    ReportLog.create(r_type: 'week', r_date: r_date, user_id: user.id, view_date: Time.now)
    render :template => 'workorders/out_template'
  end

  def month_table
    #通过用户获得其所管辖的出口
    user      = User.find(session[:user_id])
    e_name    = user.export_names
    @dls_name = user.alias

    #工单显示的是最近8个星期的统计数据,从周一到周末，如果为周一，则加多一个星期
    t_year    = Time.now.year
    t_day     = Time.now.at_beginning_of_day
    t_wb_day  = Time.now.at_beginning_of_month
    t_we_day  = Time.now.at_end_of_month
    t_month   = Time.now.month

    @out_arr = []
    #判断一下是不是当月的第一天，如果是则往往推两个月。
    if t_day.day == 1
      (1..2).each do |num|
        tmp_arr = []
        t_wb    = t_wb_day - num.month
        t_we    = t_wb.at_end_of_month
        rl      = ReportLog.where('r_date = ? and user_id = ? and r_type = "month"', t_wb, user.id)

        tmp_arr << t_wb << t_we << '所有关联出口月报表'
        tmp_arr << rl[0].view_date unless rl.blank?
        @out_arr << tmp_arr
      end
    else
      (0..1).each do |num|
        tmp_arr = []
        t_wb    = t_wb_day - num.month
        if num == 0
          t_we = t_day
        else
          t_we = t_wb.at_end_of_month
        end
        rl = ReportLog.where('r_date = ? and user_id = ? and r_type = "month"', t_wb, user.id)

        tmp_arr << t_wb << t_we << '所有关联出口月报表'
        tmp_arr << rl[0].view_date unless rl.blank?
        @out_arr << tmp_arr
      end
    end
  end

  def month_wo
    #通过用户获得其所管辖的出口
    user      = User.find(session[:user_id])
    e_name    = user.export_names
    @dls_name = user.alias
    r_date    = Time.parse params[:date]
    @out_arr  = statis_d_data(e_name, r_date, 3)

    ReportLog.create(r_type: 'month', r_date: r_date, user_id: user.id, view_date: Time.now)
    render :template => 'workorders/out_template'
  end

  def out_template

  end


end

app/helpers/workorders_helper.rb
module WorkordersHelper
  #type参数用来区分日、周、月报表类型
  def statis_d_data(e_name, date, type)
    out      = []
    p_b_date = date
    case type
      when 1
        p_e_date = p_b_date + 1.day
      when 2
        p_e_date = p_b_date + 1.week
      when 3
        p_e_date = p_b_date + 1.month
      else
        p_e_date = Time.now
    end

    e_name.each do |en|
      tmp_arr   = []
      p_records = HttpTestStatis.where('start_time >= ?  and end_time < ? and export_name = ?', p_b_date, p_e_date, en.alias)
      nega_val  = p_records.sum(:negative_statis)
      tota_val  = p_records.sum(:total_statis)
      tmp_arr << en.name << nega_val << tota_val << p_b_date << p_e_date
      puts tmp_arr
      out << tmp_arr
    end

    out
  end

  def statis_d_data1(e_name, p_max_day, p_month, p_year)
    out      = []
    p_str    = p_year.to_s + '-' + p_month.to_s + '-' + p_max_day.to_s
    p_b_date = Time.parse(p_str)
    p_e_date = p_b_date + 1.day
    e_name.each do |en|
      tmp_arr   = []
      p_records = HttpTestStatis.where('start_time >= ?  and end_time < ? and export_name = ?', p_b_date, p_e_date, en.alias)
      nega_val  = p_records.sum(:negative_statis)
      tota_val  = p_records.sum(:total_statis)
      tmp_arr << en.name << nega_val << tota_val << p_b_date
      puts tmp_arr
      out << tmp_arr
    end

    out
  end
end

app/views/workorders/index.html.erb
<%= provide(:body_id, 'index') %>
<%= provide(:result, '工单查看') %>

<div class="container-fluid content-wrapper">
  <div class="row-fluid">
    <div class="span12">
      <div class="hero-unit">
        <button type="button" class="close hidden-phone" data-dismiss="alert">&times;</button>
        <h1>工单查看</h1>
        <p>
          工单报表可以按日、周、月进行报表查看，可以指定日期进行下载相关报表，报表评估数据根据相关评分标准生成。
          如修改了相应的评分标准，不影响已生成的报表数据，只对往后的报表数据有影响，如对结果有异议，可申请核对。
        </p>
        <br/>
        <p class="hidden-phone">
          <a class="btn btn-info btn-large pull-right">详细指南请猛击此处 &raquo;...</a>
        </p>
      </div>
    </div>
  </div>
  <a href="workorders/wo_table" class="btn btn-info btn-large">出口统计得分日报表</a>
  <a href="workorders/week_table" class="btn btn-info btn-large">出口统计得分周报表</a>
  <a href="workorders/month_table" class="btn btn-info btn-large">出口统计得分月报表</a>
  <p></p>


  <div class="row-fluid">
    <div class="span12">
      <h4 class="title">名言警句</h4>

      <div class="squiggly-border"></div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <blockquote>
        <p>
          Etiam varius erat in nisl egestas id auctor lacus consectetur.
          Ut dui risus, auctor a malesuada volutpat, tempus sit amet arcu.
        </p>
        <small class="pull-right">Jane Doe via Mobile</small>
      </blockquote>
    </div>
  </div>
</div>

app/views/workorders/month_table.html.erb
<%= provide(:body_id, 'index') %>
<%= provide(:result, '工单查看') %>

<div class="container-fluid content-wrapper">
  <div class="row-fluid">
    <div class="span12">
      <div class="hero-unit">
        <button type="button" class="close hidden-phone" data-dismiss="alert">&times;</button>
        <h1>代理商工单查看</h1>

        <p>
          工单列表根据出口对各个测试网站的评分进行统计，主要统计负分、总分两项指标。<br/>
        </p>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <ul class="breadcrumb">
        <li>
          <a href="/">
            <i class="radmin-icon radmin-home"></i>
            首页
          </a>
          <span class="divider">/</span>
        </li>
        <li>
          <a href="/workorders">
            <i class="radmin-icon radmin-file"></i>
            工单查看
          </a>
          <span class="divider">/</span>
        </li>
        <li class="active">
          <i class="radmin-icon radmin-file"></i>
          查看出口周报表
        </li>
      </ul>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <div class="row-fluid hidden-desktop hidden-phone">
        <div class="span12">
          <h4 class="title">[<%= @dls_name %>] 所辖出口得分排名表如下示：</h4>

          <div class="squiggly-border"></div>
          <table class="table table-striped table-bordered table-radmin">
            <thead>
            <tr>
              <th style="text-align:center;">日期</th>
              <th style="text-align:center;">内容</th>
              <th style="text-align:center;">动作</th>
              <th style="text-align:center;">查看日期</th>
            </tr>
            </thead>
            <tbody>
            <% @out_arr.each_with_index do |line, i| %>
              <tr>
                <td style="text-align:center;">
                  <%= line[0].strftime('%Y年-%m月%d日') %> - <%= line[1].strftime('%Y年-%m月%d日') %>
                </td>
                <td style="text-align:center;"><%= line[2] %></td>
                <td style="text-align:center;">
                  <a class="btn btn-small btn-info" href="<%= month_wo_workorders_path(date: line[0]) %>">
                    <i class="icon-edit icon-white"></i>
                    查看
                  </a>
                </td>
                <td style="text-align:center;">
                  <% unless line[3].blank? %>
                    <%= line[3].strftime('%Y年-%m月%d日 %H:%M:%S') %>
                  <% end %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>

      </div>
    </div>
  </div>

  <p></p>

  <div class="row-fluid">
    <div class="span12">
      <h4 class="title">名言警句</h4>

      <div class="squiggly-border"></div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <blockquote>
        <p>
          Etiam varius erat in nisl egestas id auctor lacus consectetur.
          Ut dui risus, auctor a malesuada volutpat, tempus sit amet arcu.
        </p>
        <small class="pull-right">Jane Doe via Mobile</small>
      </blockquote>
    </div>
  </div>
</div>

app/views/workorders/out_template.html.erb
<%= provide(:body_id, 'index') %>
<%= provide(:result, '工单查看') %>

<div class="container-fluid content-wrapper">
  <div class="row-fluid">
    <div class="span12">
      <div class="hero-unit">
        <button type="button" class="close hidden-phone" data-dismiss="alert">&times;</button>
        <h1>代理商工单查看</h1>

        <p>
          工单列表根据出口对各个测试网站的评分进行统计，主要统计负分、总分两项指标。<br/>
        </p>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <ul class="breadcrumb">
        <li>
          <a href="/">
            <i class="radmin-icon radmin-home"></i>
            首页
          </a>
          <span class="divider">/</span>
        </li>
        <li>
          <a href="/workorders">
            <i class="radmin-icon radmin-file"></i>
            工单查看
          </a>
          <span class="divider">/</span>
        </li>
        <li>
          <a href="#">
            <i class="radmin-icon radmin-file"></i>
            选择日周月报表
          </a>
          <span class="divider">/</span>
        </li>
        <li class="active">
          <i class="radmin-icon radmin-file"></i>
          查看日周月报表
        </li>
      </ul>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <div class="row-fluid hidden-desktop hidden-phone">
        <div class="span12">
          <h4 class="title">[<%= @dls_name %>] 所辖出口得分排名表如下示：</h4>

          <div class="squiggly-border"></div>
          <table class="table table-striped table-bordered table-radmin">
            <thead>
            <tr>
              <th style="text-align:center;">出口名称</th>
              <th style="text-align:center;">负值</th>
              <th style="text-align:center;">总分</th>
              <th style="text-align:center;">日期</th>
              <th style="text-align:center;">详细信息</th>
            </tr>
            </thead>
            <tbody>
            <% @out_arr.each_with_index do |line, i| %>
              <tr>
                <td style="text-align:center;"><%= link_to line[0],controller: 'reports',action:'r_graph',:en => line[0] %></td>
                <td style="text-align:center;">
                  <% if line[1].to_s.to_f < 0 %>
                    <span class="label label-important"><%= number_with_precision line[1].to_s.to_f %></span>
                  <% else %>
                    <span class="label label-info"><%= number_with_precision line[1].to_s.to_f %></span>
                  <% end %>
                </td>
                <td style="text-align:center;">
                  <% if line[2].to_s.to_f < 0 %>
                    <span class="label label-important"><%= number_with_precision line[2].to_s.to_f %></span>
                  <% else %>
                    <span class="label label-info"><%= number_with_precision line[2].to_s.to_f %></span>
                  <% end %>
                </td>
                <td style="text-align:center;">
                  <%= line[3].strftime('%Y年-%m月%d日') %> - <%= line[4].strftime('%Y年-%m月%d日') %>
                </td>
                <td style="text-align:center;">
                  <a class="btn btn-small btn-info" href="<%= export_detail_workorders_path(bdate: line[3],edate:line[4],ename: line[0]) %>">
                    <i class="icon-edit icon-white"></i>
                    查看详细信息
                  </a>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>

      </div>
    </div>
  </div>

  <p></p>

  <div class="row-fluid">
    <div class="span12">
      <h4 class="title">名言警句</h4>

      <div class="squiggly-border"></div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <blockquote>
        <p>
          Etiam varius erat in nisl egestas id auctor lacus consectetur.
          Ut dui risus, auctor a malesuada volutpat, tempus sit amet arcu.
        </p>
        <small class="pull-right">Jane Doe via Mobile</small>
      </blockquote>
    </div>
  </div>
</div>

app/views/workorders/week_table.html.erb
<%= provide(:body_id, 'index') %>
<%= provide(:result, '工单查看') %>

<div class="container-fluid content-wrapper">
  <div class="row-fluid">
    <div class="span12">
      <div class="hero-unit">
        <button type="button" class="close hidden-phone" data-dismiss="alert">&times;</button>
        <h1>代理商工单查看</h1>

        <p>
          工单列表根据出口对各个测试网站的评分进行统计，主要统计负分、总分两项指标。<br/>
        </p>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <ul class="breadcrumb">
        <li>
          <a href="/">
            <i class="radmin-icon radmin-home"></i>
            首页
          </a>
          <span class="divider">/</span>
        </li>
        <li>
          <a href="/workorders">
            <i class="radmin-icon radmin-file"></i>
            工单查看
          </a>
          <span class="divider">/</span>
        </li>
        <li class="active">
          <i class="radmin-icon radmin-file"></i>
          查看出口周报表
        </li>
      </ul>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <div class="row-fluid hidden-desktop hidden-phone">
        <div class="span12">
          <h4 class="title">[<%= @dls_name %>] 所辖出口得分排名表如下示：</h4>

          <div class="squiggly-border"></div>
          <table class="table table-striped table-bordered table-radmin">
            <thead>
            <tr>
              <th style="text-align:center;">日期</th>
              <th style="text-align:center;">内容</th>
              <th style="text-align:center;">动作</th>
              <th style="text-align:center;">查看日期</th>
            </tr>
            </thead>
            <tbody>
            <% @out_arr.each_with_index do |line, i| %>
              <tr>
                <td style="text-align:center;">
                  <%= line[0].strftime('%Y年-%m月%d日') %> - <%= line[1].strftime('%Y年-%m月%d日') %>
                </td>
                <td style="text-align:center;"><%= line[2] %></td>
                <td style="text-align:center;">
                  <a class="btn btn-small btn-info" href="<%= week_wo_workorders_path(date: line[0]) %>">
                    <i class="icon-edit icon-white"></i>
                    查看
                  </a>
                </td>
                <td style="text-align:center;">
                  <% unless line[3].blank? %>
                    <%= line[3].strftime('%Y年-%m月%d日 %H:%M:%S') %>
                  <% end %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>

      </div>
    </div>
  </div>

  <p></p>

  <div class="row-fluid">
    <div class="span12">
      <h4 class="title">名言警句</h4>

      <div class="squiggly-border"></div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <blockquote>
        <p>
          Etiam varius erat in nisl egestas id auctor lacus consectetur.
          Ut dui risus, auctor a malesuada volutpat, tempus sit amet arcu.
        </p>
        <small class="pull-right">Jane Doe via Mobile</small>
      </blockquote>
    </div>
  </div>
</div>

app/views/workorders/wo_table.html.erb
<%= provide(:body_id, 'index') %>
<%= provide(:result, '工单查看') %>

<div class="container-fluid content-wrapper">
  <div class="row-fluid">
    <div class="span12">
      <div class="hero-unit">
        <button type="button" class="close hidden-phone" data-dismiss="alert">&times;</button>
        <h1>代理商工单查看</h1>

        <p>
          工单列表根据出口对各个测试网站的评分进行统计，主要统计负分、总分两项指标。<br/>
        </p>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <ul class="breadcrumb">
        <li>
          <a href="/">
            <i class="radmin-icon radmin-home"></i>
            首页
          </a>
          <span class="divider">/</span>
        </li>
        <li>
          <a href="/workorders">
            <i class="radmin-icon radmin-file"></i>
            工单查看
          </a>
          <span class="divider">/</span>
        </li>
        <li class="active">
          <i class="radmin-icon radmin-file"></i>
          查看出口日报表
        </li>
      </ul>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <div class="row-fluid hidden-desktop hidden-phone">
        <div class="span12">
          <h4 class="title">[<%= @dls_name %>] 所辖出口得分排名表如下示：</h4>

          <div class="squiggly-border"></div>
          <table class="table table-striped table-bordered table-radmin">
            <thead>
            <tr>
              <th style="text-align:center;">日期</th>
              <th style="text-align:center;">内容</th>
              <th style="text-align:center;">动作</th>
              <th style="text-align:center;">查看日期</th>
            </tr>
            </thead>
            <tbody>
            <% @out_arr.each_with_index do |line, i| %>
              <tr>
                <td style="text-align:center;"><%= line[0].strftime('%Y年-%m月%d日') %></td>
                <td style="text-align:center;"><%= line[1] %></td>
                <td style="text-align:center;">
                  <a class="btn btn-small btn-info" href="<%= day_wo_workorders_path(date: line[0]) %>">
                    <i class="icon-edit icon-white"></i>
                    查看
                  </a>
                </td>
                <td style="text-align:center;">
                  <% unless line[2].blank? %>
                    <%= line[2].strftime('%Y年-%m月%d日 %H:%M:%S') %>
                  <% end %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>

      </div>
    </div>
  </div>

  <p></p>

  <div class="row-fluid">
    <div class="span12">
      <div class="well center">
        <div class="pagination pagination-small center offset4">
          <%= will_paginate @out_arr, :inner_window => 2 %>
        </div>
        <div class="offset4">
          统计信息：一共有 <%= @out_arr.total_entries %>  条,当前第 <%= @out_arr.current_page %> 页, 共
          <% if (@out_arr.total_entries % @out_arr.per_page) ==0 %>
            <%= (@out_arr.total_entries / @out_arr.per_page) %> 页.
          <% else %>
            <%= (@out_arr.total_entries / @out_arr.per_page) +1 %> 页
          <% end %>
        </div>

      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <h4 class="title">名言警句</h4>

      <div class="squiggly-border"></div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <blockquote>
        <p>
          Etiam varius erat in nisl egestas id auctor lacus consectetur.
          Ut dui risus, auctor a malesuada volutpat, tempus sit amet arcu.
        </p>
        <small class="pull-right">Jane Doe via Mobile</small>
      </blockquote>
    </div>
  </div>
</div>