config/routes.rb
Wjgzxt::Application.routes.draw do
  match 'log' => 'log_action#index'
  match 'log(/:action)' => 'log_action#(:action)'
  resources :log_action,only:[:index] do
    collection do
      get 'index','neg_r','neg_ru'
    end
  end

  resources :pwd_modify, only: [] do
    collection do
      get 'modify', 'p_modify'
    end
  end

  resources :domain, only: [] do
    collection do
      get 'validate', 'test', 'dfileupload'
      post 'upload'
    end
  end

  resources :export, only: [] do
    member do
      get 'modify', 'chg_status', 'del'
    end
    collection do
      get 'index', 'flag', 'perm_deni'
      get 'mdf', 'add_flag', 'p_add_flag'
    end
  end

  resources :rdata, only: [] do
    collection do
      get 'index','q_rdata_report'
    end
  end

  match 'login' => 'login#index'
  get 'login/index'
  post "login/login"
  get "login/logout"

  match 'workorders' => 'workorders#index'
  resources :workorders, only: [] do
    collection do
      get 'index', 'day_wo', 'week_wo', 'month_wo', 'wo_table', 'export_detail', 'week_table', 'month_table'
    end
  end

  match 'graphs' => 'graphs#index'
  resources :graphs, only: [] do
    collection do
      get 'index', 'data_json'
    end
  end

  resources :web_hit_rate, only: [] do
    collection do
      get 'time_r', 'select_day_report', 'select_month_report', 'index', 'day_r', 'month_r', 'list_day', 'list_time', 'list_locale'
      post 'day_r', 'month_r'
    end
  end

  match 'whr/' => 'web_hit_rate#index'

  resources :param_setting, only: [] do
    collection do
      get 'http', 'ping', 'route', 'video', 'adduser', 'mng_user', 'interaction', 'view_interaction', 'del_interaction', 'p_adduser'
      get 'u_user', 's_user', 'd_user', 'p_u_user', 'p_interaction'
      post 'p_adduser'
    end
  end

  match 'reports/get_data(.:format)' => 'reports#get_data'
  resources :reports, only: [] do
    collection do
      get 'export_rep', 'get_data', 'r_graph', 'locale_detail'
      get 'select_date_report', 'select_day_report', 'select_week_report', 'select_month_report'
      get 'time_report', 'day_report', 'week_report', 'month_report', 'day_report_csv', 'week_report_csv', 'month_report_csv'
      get 'date2time_report', 'date2day_report', 'date2week_report', 'date2month_report'
      post 'day_report', 'week_report', 'month_report'
    end
  end

  get 'reports/export_ranking'

  post 'reports/website_ranking'

  get 'reports/website_select'

  get 'reports/locale_ranking'

  get 'welcome/index'

  match 'reports/' => 'reports#index'
  match 'welcome/' => 'welcome#index'

  root :to => 'login#index'

end

app/controllers/export_controller.rb
#encoding : utf-8
class ExportController < ApplicationController
  before_filter :user_level, except: [:perm_deni]

  def flag
    @en = ExportName.all
  end

  def add_flag
  end

  def p_add_flag
    e_no   = params[:e_no].to_s.strip
    e_name = params[:e_name].to_s.strip
    en     = ExportName.new(name: e_name, status: 0, user_id: session[:user_id], alias: e_no)
    if en.save
      flash[:success] = '添加出口编号成功。'
    else
      flash[:error] = '更新出口编号失败，可能编号或者名称存在重复，请检查。'
    end
    redirect_to action: 'add_flag'
  end

  def modify
    @en = ExportName.find(params[:id])
  end

  def mdf
    id     = params[:id].to_s.strip
    e_name = params[:name].to_s.strip
    ExportName.find(id).update_attribute('name', e_name)
    redirect_to action: 'flag'
  end

  def chg_status
    @en = ExportName.find(params[:id])
    if @en.status == 0
      @en.update_attribute('status',1)
    else
      @en.update_attribute('status',0)
    end
    flash[:success] = '更新出口状态成功。'
    redirect_to action: 'flag'
  end

  def del
    @en = ExportName.find(params[:id])
    @en.destroy
    flash[:success] = '删除出口编号成功。'
    redirect_to action: 'flag'
  end

  def block
  end

  def perm_deni

  end

  private
  def user_level
    if current_user.level < 3
      redirect_to action: 'perm_deni'
    end

  end
end

app/helpers/export_helper.rb
module ExportHelper
end

app/views/export/add_flag.html.erb
<%= provide(:body_id, 'components') %>
<%= provide(:result, '系统说明') %>

<div class="container-fluid content-wrapper">
  <div class="row-fluid">
    <div class="span12">
      <div class="hero-unit">
        <button type="button" class="close hidden-phone" data-dismiss="alert">&times;</button>
        <h1>添加新的出口编号信息</h1>

        <div class="row-fluid hidden-desktop hidden-phone">
          <div class="span12">
            <p>
              关于实施出口编号和管理的通知<br>
              为了便于系统统计，规定所有纳入到出口感知质量测试的出口名称全部采用编号命名方式，具体编号规则如下：<br>
              1、电信出口以数字1开头，再加上三位数字，形式为：1XXX。从1001开始顺序编号。<br>
              2、联通出口以数字2开头，再加上三位数字，形式为：2XXX。从2001开始顺序编号。<br>
              3、出口编号属于一次性使用资源：当出口关停后，该出口对应的编号也作废，不再循环使用。如出口只是更改名称（例如接入运营商调整等），则可使用回原来的编号。
              编号与实际出口对应关系要在出口评分统计系统中录入。当新增一个出口，要及时在对应表中为该出口分配新的编号。当出口更改名称时，要在对应表中该出口编号下修改出口名称。 <br/>
            </p>
          </div>
        </div>
        <p></p>

      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <ul class="breadcrumb">
        <li>
          <a href="/">
            <i class="radmin-icon radmin-home"></i>
            首页
          </a>
          <span class="divider">/</span>
        </li>
        <li>
          <a href="flag">
            <i class="radmin-icon radmin-file"></i>
            出口标识
          </a>
          <span class="divider">/</span>
        </li>
        <li class="active">
          <i class="radmin-icon radmin-file"></i>
          新增出口标识
        </li>
      </ul>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <div class="row-fluid hidden-desktop hidden-phone">
        <div class="span12">
          <h4 class="title">添加出口编号相关资料</h4>

          <div class="squiggly-border"></div>
          <form class="well form-horizontal" action="p_add_flag" method="get">
            <fieldset>
              <legend class="align-center">请填写出口编号对应资料</legend>
              <div class="control-group offset2">
                <%= label_tag 'e_no','出口编号:',class:'control-label pull-right' %>
                <div class="controls">
                  <%= text_field_tag 'e_no',nil, class: 'input_xlarge' %>
                </div>
              </div>
              <div class="control-group offset2">
                <%= label_tag 'e_name','出口名称:',class:'control-label pull-right' %>
                <div class="controls">
                  <%= text_field_tag 'e_name',nil, class: 'input_xlarge' %>
                </div>
              </div>

              <button class="btn btn-large btn-info span4 offset4" type="submit">提 交</button>
            </fieldset>
          </form>

        </div>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <h4 class="title">名言警句</h4>

      <div class="squiggly-border"></div>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span12">
      <blockquote>
        <p>
          当一切似乎毫无希望时，我看着切石工人在他的石头上，敲击了上百次，而不见任何裂痕出现。
          但在第一百零一次时，石头被劈成两半。我体会到，并非那一击，而是前面的敲打使它裂开。
        </p>
        <small class="pull-right">贾柯·瑞斯</small>
      </blockquote>
    </div>
  </div>
</div>

app/views/export/flag.html.erb
<%= provide(:body_id, 'components') %>
<%= provide(:result, '系统说明') %>

<div class="container-fluid content-wrapper">
  <div class="row-fluid">
    <div class="span12">
      <div class="hero-unit">
        <button type="button" class="close hidden-phone" data-dismiss="alert">&times;</button>
        <h1>出口编号信息</h1>

        <div class="row-fluid hidden-desktop hidden-phone">
          <div class="span12">
            <p>
              关于实施出口编号和管理的通知<br>
              为了便于系统统计，规定所有纳入到出口感知质量测试的出口名称全部采用编号命名方式，具体编号规则如下：<br>
              1、电信出口以数字1开头，再加上三位数字，形式为：1XXX。从1001开始顺序编号。<br>
              2、联通出口以数字2开头，再加上三位数字，形式为：2XXX。从2001开始顺序编号。<br>
              3、出口编号属于一次性使用资源：当出口关停后，该出口对应的编号也作废，不再循环使用。如出口只是更改名称（例如接入运营商调整等），则可使用回原来的编号。
              编号与实际出口对应关系要在出口评分统计系统中录入。当新增一个出口，要及时在对应表中为该出口分配新的编号。当出口更改名称时，要在对应表中该出口编号下修改出口名称。 <br/>
              出口原始信息是由飞思达所提供的测试数据中提取，为了方便同后台维护部门核对，可添加相应的出口名称进行关联。<br/>
            </p>
          </div>
        </div>
        <p></p>

        <p class="hidden-phone">
          <a class="btn btn-info btn-large pull-right">详细指南请猛击此处 &raquo;</a>
        </p>
      </div>
    </div>
  </div>

  <a href="add_flag" class="btn btn-info btn-large">添加出口编号信息</a>

  <p></p>

  <div class="row-fluid">
    <div class="span12">
      <div class="row-fluid hidden-desktop hidden-phone">
        <div class="span12">
          <h4 class="title">所有出口编号相关资料</h4>

          <div class="squiggly-border"></div>
          <table class="table table-striped table-bordered table-radmin">
            <thead>
            <tr>
              <th style="text-align:center;">出口编号</th>
              <th style="text-align:center;">出口名称</th>
              <th style="text-align:center;">状态</th>
              <th style="text-align:center;" colspan="3">操作选项</th>
            </tr>
            </thead>
            <tbody>
            <% @en.each do |u| %>
              <tr>
                <td style="text-align:center;"><%= u.alias %></td>
                <td style="text-align:center;"><%= u.name %></td>
                <td style="text-align:center;">
                  <% if u.status== 0 %>
                    正常
                  <% else %>
                    <span class="label label-warning">停用</span>
                  <% end %>
                </td>

                <td style="text-align:center;">
                  <a class="btn btn-small btn-info" href="<%= modify_export_path(u) %>">
                    <i class="icon-edit icon-white"></i>
                    更新
                  </a>
                </td>

                <td style="text-align:center;">
                  <a class="btn btn-small btn-info" href="<%= chg_status_export_path(u) %>">
                    <i class="icon-edit icon-white"></i>
                    <% if u.status== 0 %>
                      停用
                    <% else %>
                      正常
                    <% end %>
                  </a>
                </td>

                <td style="text-align:center;">
                  <a class="btn btn-small btn-danger" href="<%= del_export_path(u) %>">
                    <i class="icon-edit icon-white"></i>
                    删除
                  </a>
                </td>
              </tr>
            <% end %>

            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <h4 class="title">名言警句</h4>

      <div class="squiggly-border"></div>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span12">
      <blockquote>
        <p>
          当一切似乎毫无希望时，我看着切石工人在他的石头上，敲击了上百次，而不见任何裂痕出现。
          但在第一百零一次时，石头被劈成两半。我体会到，并非那一击，而是前面的敲打使它裂开。
        </p>
        <small class="pull-right">贾柯·瑞斯</small>
      </blockquote>
    </div>
  </div>
</div>

app/views/export/modify.html.erb
<%= provide(:body_id, 'components') %>
<%= provide(:result, '系统说明') %>

<div class="container-fluid content-wrapper">
  <div class="row-fluid">
    <div class="span12">
      <div class="hero-unit">
        <button type="button" class="close hidden-phone" data-dismiss="alert">&times;</button>
        <h1>出口标识信息</h1>

        <div class="row-fluid hidden-desktop hidden-phone">
          <div class="span12">
            <p>
              出口原始信息是由飞思达所提供的测试数据中提取，为了方便同后台维护部门核对，可添加相应的备注信息进行关联。<br/>
            </p>
          </div>
        </div>
        <p></p>

        <p class="hidden-phone">
          <a class="btn btn-info btn-large pull-right">详细指南请猛击此处 &raquo;</a>
        </p>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <ul class="breadcrumb">
        <li>
          <a href="/">
            <i class="radmin-icon radmin-home"></i>
            首页
          </a>
          <span class="divider">/</span>
        </li>
        <li>
          <a href="/export/flag">
            <i class="radmin-icon radmin-file"></i>
            出口标识
          </a>
          <span class="divider">/</span>
        </li>
        <li class="active">
          <i class="radmin-icon radmin-file"></i>
          更新出口标识
        </li>
      </ul>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <form class="well form-horizontal" action="/export/mdf" method="get">
        <div class="row-fluid hidden-desktop hidden-phone">
          <div class="span12">
            <h4 class="title">出口标识资料修改</h4>

            <div class="squiggly-border"></div>
            <table class="table table-striped table-bordered table-radmin">
              <thead>
              <tr>
                <th style="text-align:center;">出口编号</th>
                <th style="text-align:center;">出口名称</th>
                <th style="text-align:center;">操作选项</th>
              </tr>
              </thead>
              <tbody>
              <tr>
                <td style="text-align:center;">
                  <input type="hidden" name="id" value="<%= @en.id %>">
                  <%=  @en.alias %>
                </td>
                <td style="text-align:center;">
                  <%= text_field_tag :name, @en.name, :class => 'input-xlarge' %>
                </td>
                <td style="text-align:center;">
                  <button class="btn btn-info" type="submit">
                    更 新
                  </button>
                </td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
      </form>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <h4 class="title">名言警句</h4>

      <div class="squiggly-border"></div>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span12">
      <blockquote>
        <p>
          当一切似乎毫无希望时，我看着切石工人在他的石头上，敲击了上百次，而不见任何裂痕出现。
          但在第一百零一次时，石头被劈成两半。我体会到，并非那一击，而是前面的敲打使它裂开。
        </p>
        <small class="pull-right">贾柯·瑞斯</small>
      </blockquote>
    </div>
  </div>
</div>

app/views/export/perm_deni.html.erb
<%= provide(:body_id, 'index') %>
<%= provide(:result, '系统说明') %>

<div class="container-fluid content-wrapper">
  <div class="row-fluid">
    <div class="span12">
      <div class="hero-unit">
        <button type="button" class="close hidden-phone" data-dismiss="alert">&times;</button>
        <h1>权限不够</h1>

        <div class="row-fluid hidden-desktop hidden-phone">
          <div class="span12">
            <p>
              由于您的权限不够，我们暂时先屏蔽了部分功能，如您确实有需求，可向管理员提出申请。<br/>
            </p>
          </div>
        </div>
        <p></p>

        <p class="hidden-phone">
          <a class="btn btn-info btn-large pull-right">详细指南请猛击此处 &raquo;</a>
        </p>
      </div>
    </div>
  </div>

  <p></p>

  <div class="row-fluid">
    <div class="span12">
      <h4 class="title">名言警句</h4>

      <div class="squiggly-border"></div>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span12">
      <blockquote>
        <p>
          当一切似乎毫无希望时，我看着切石工人在他的石头上，敲击了上百次，而不见任何裂痕出现。
          但在第一百零一次时，石头被劈成两半。我体会到，并非那一击，而是前面的敲打使它裂开。
        </p>
        <small class="pull-right">贾柯·瑞斯</small>
      </blockquote>
    </div>
  </div>
</div>